export const mockNotices = [
  {
    id: '1',
    type: 'general',
    title: 'End of Semester General Assembly',
    body: 'All students are required to attend the end-of-semester general assembly scheduled for Friday, 14th March at 10:00 AM in the main auditorium. Attendance will be taken.',
    author: 'Dean of Students',
    course: null,
    date: '2026-03-10T08:00:00Z',
  },
  {
    id: '2',
    type: 'exam',
    title: 'Mid-Semester Examination Timetable',
    body: 'The mid-semester examination timetable has been released. Please check the student portal for your specific schedule. Examinations run from 17th to 21st March.',
    author: 'Examinations Office',
    course: null,
    date: '2026-03-08T09:00:00Z',
  },
  {
    id: '3',
    type: 'assignment',
    title: 'CSC 302: Data Structures Assignment 2 Due',
    body: 'Assignment 2 covering Binary Trees and Graph Algorithms is due on 15th March 2026 by 11:59 PM. Submit via the course portal. Late submissions will not be accepted.',
    author: 'Dr. Mensah',
    course: 'CSC 302',
    date: '2026-03-07T12:00:00Z',
  },
  {
    id: '4',
    type: 'resource',
    title: 'New Study Materials: Operating Systems',
    body: 'Supplementary study materials for CSC 401 Operating Systems have been uploaded to the library portal. Students are encouraged to review them before the upcoming exam.',
    author: 'CSC Department',
    course: 'CSC 401',
    date: '2026-03-06T14:30:00Z',
  },
  {
    id: '5',
    type: 'general',
    title: 'Library Extended Hours — Exam Season',
    body: 'The university library will be open until midnight from 10th to 25th March to support students during exam preparation. Quiet zones will be strictly enforced.',
    author: 'Library Services',
    course: null,
    date: '2026-03-05T07:00:00Z',
  },
  {
    id: '6',
    type: 'assignment',
    title: 'ENG 201: Technical Report Submission',
    body: 'Your technical report for ENG 201 must be submitted by 12th March 2026. Ensure you follow the prescribed format. Reports must be uploaded as PDF files.',
    author: 'Prof. Asante',
    course: 'ENG 201',
    date: '2026-03-04T10:00:00Z',
  },
  {
    id: '7',
    type: 'exam',
    title: 'MTH 101: Calculus Resit Examination',
    body: 'Students who did not pass the MTH 101 Calculus examination are reminded that the resit is scheduled for 20th March at 8:00 AM in Hall B. Please bring your ID card.',
    author: 'Mathematics Department',
    course: 'MTH 101',
    date: '2026-03-03T11:00:00Z',
  },
  {
    id: '8',
    type: 'resource',
    title: 'Database Systems: Past Questions Available',
    body: 'Past exam questions for CSC 303 Database Systems are now available on the department noticeboard and online portal. These cover the last five years of examinations.',
    author: 'CSC Department',
    course: 'CSC 303',
    date: '2026-03-02T09:00:00Z',
  },
]

export const mockDeadlines = [
  {
    id: 'd1',
    title: 'CSC 302: Assignment 2',
    course: 'CSC 302',
    dueDate: '2026-03-15T23:59:00Z',
    type: 'assignment',
  },
  {
    id: 'd2',
    title: 'ENG 201: Technical Report',
    course: 'ENG 201',
    dueDate: '2026-03-12T23:59:00Z',
    type: 'assignment',
  },
  {
    id: 'd3',
    title: 'Mid-Semester Examinations Begin',
    course: null,
    dueDate: '2026-03-17T08:00:00Z',
    type: 'exam',
  },
  {
    id: 'd4',
    title: 'MTH 101 Resit Exam',
    course: 'MTH 101',
    dueDate: '2026-03-20T08:00:00Z',
    type: 'exam',
  },
  {
    id: 'd5',
    title: 'General Assembly',
    course: null,
    dueDate: '2026-03-14T10:00:00Z',
    type: 'general',
  },
]
