export const mockNotices = [
  // ── Pinned ──────────────────────────────────────────────────────────────────
  {
    id: "1",
    type: "assignment",
    title: "CSM 395 – Data Structures Assignment #3",
    body: `Submit your implementation of AVL trees with full rotation logic. Must include test cases.\n\nRequirements:\n- Implementation in Python or Java\n- Full rotation logic (LL, RR, LR, RL rotations)\n- At least 10 unit test cases covering edge cases\n- A README with build and run instructions\n\nSubmit via the portal below. Late submissions will be penalised by 10% per day.`,
    author: "Kwame Asante",
    authorRole: "Course Rep",
    authorAvatar: null,
    course: "CSC 395",
    date: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    dueDate: "2026-03-22T23:59:00Z",
    commentCount: 7,
    pinned: true,
    attachments: [
      { id: "a1", name: "Assignment_3_Brief.pdf", type: "pdf", size: "245 KB" },
      { id: "a2", name: "sample_avl_output.png", type: "image", size: "88 KB" },
    ],
    links: [
      {
        id: "l1",
        label: "Submission Portal",
        url: "https://knust.edu.gh/student/submit",
      },
      {
        id: "l2",
        label: "AVL Tree Reference Slides",
        url: "https://visualgo.net/en/bst",
      },
    ],
    comments: [
      {
        id: "c1",
        author: "Ama Owusu",
        authorRole: "Student",
        body: "Can we use any programming language or does it have to be Java?",
        date: "2026-03-10T09:15:00Z",
        replies: [
          {
            id: "c1r1",
            author: "Kwame Asante",
            authorRole: "Course Rep",
            body: "Prof mentioned Python or Java are both fine. No other languages.",
            date: "2026-03-10T10:00:00Z",
            replies: [],
          },
        ],
      },
      {
        id: "c2",
        author: "Kofi Mensah",
        authorRole: "Student",
        body: "Is the README file mandatory or optional?",
        date: "2026-03-11T14:20:00Z",
        replies: [],
      },
      {
        id: "c3",
        author: "Abena Frempong",
        authorRole: "Student",
        body: "Does pair work count or is it strictly individual?",
        date: "2026-03-12T08:45:00Z",
        replies: [
          {
            id: "c3r1",
            author: "Kwame Asante",
            authorRole: "Course Rep",
            body: "Strictly individual. The brief says so.",
            date: "2026-03-12T09:10:00Z",
            replies: [],
          },
        ],
      },
    ],
  },

  // ── General ─────────────────────────────────────────────────────────────────
  {
    id: "2",
    type: "general",
    title: "Updated Class Schedule – Network Security",
    body: `The Network Security class originally scheduled for Wednesday has been moved to Thursday at 10:00 AM. The venue remains Lab 3 (second floor, CS Building).\n\nThis change applies to all sections. If you have any scheduling conflicts with other courses, please contact the department office by Monday so the timetable team can assist you.`,
    author: "Dr. Abena Frimpong",
    authorRole: "Lecturer",
    authorAvatar: null,
    course: null,
    date: "2026-02-28T10:00:00Z",
    dueDate: null,
    commentCount: 18,
    pinned: false,
    attachments: [
      {
        id: "a1",
        name: "Updated_Schedule_Feb.pdf",
        type: "pdf",
        size: "180 KB",
      },
    ],
    links: [
      {
        id: "l1",
        label: "Department Schedule Portal",
        url: "https://knust.edu.gh/timetable",
      },
    ],
    comments: [
      {
        id: "c1",
        author: "Nana Boateng",
        authorRole: "Student",
        body: "Does this apply to the Thursday lab session as well, or just the lecture?",
        date: "2026-02-28T11:30:00Z",
        replies: [
          {
            id: "c1r1",
            author: "Dr. Abena Frimpong",
            authorRole: "Lecturer",
            body: "Yes, the lab session time is also adjusted. Check the portal for the full updated timetable.",
            date: "2026-02-28T12:45:00Z",
            replies: [],
          },
        ],
      },
      {
        id: "c2",
        author: "Yaw Darko",
        authorRole: "Student",
        body: "Is the lecture hall also Lab 3 or a different venue?",
        date: "2026-02-28T13:00:00Z",
        replies: [],
      },
    ],
  },
  {
    id: "5",
    type: "general",
    title: "End of Semester General Assembly",
    body: `All students are required to attend the end-of-semester general assembly scheduled for Friday, 14th March at 10:00 AM in the main auditorium.\n\nAttendance will be taken. Items on the agenda include semester review, student welfare updates, and departmental announcements.\n\nDress code: formal.`,
    author: "Dean of Students",
    authorRole: "Administration",
    authorAvatar: null,
    course: null,
    date: "2026-03-10T08:00:00Z",
    dueDate: null,
    commentCount: 12,
    pinned: false,
    attachments: [],
    links: [],
    comments: [],
  },
  {
    id: "10",
    type: "general",
    title: "Departmental Sports Day – Friday 28th March",
    body: `The Computer Science Department is hosting its annual Sports Day on Friday, 28th March at the university sports complex.\n\nAll students are encouraged to participate. Events include football, volleyball, table tennis, and relay races. Registration closes Thursday evening.\n\nFood and refreshments will be provided. Wear casual clothing.`,
    author: "CSC Department",
    authorRole: "Department",
    authorAvatar: null,
    course: null,
    date: "2026-03-15T09:00:00Z",
    dueDate: null,
    commentCount: 22,
    pinned: false,
    attachments: [],
    links: [
      {
        id: "l1",
        label: "Register for Events",
        url: "https://forms.google.com/sports-day-registration",
      },
    ],
    comments: [],
  },
  {
    id: "11",
    type: "general",
    title: "Library Hours Extended During Exam Period",
    body: `The main library will be open from 6:00 AM to midnight during the exam period (25th March – 10th April).\n\nStudy rooms can be booked online up to 48 hours in advance. Quiet zones are strictly enforced. Group bookings of up to 6 are available on the second floor.`,
    author: "Library Services",
    authorRole: "Administration",
    authorAvatar: null,
    course: null,
    date: "2026-03-14T11:00:00Z",
    dueDate: null,
    commentCount: 5,
    pinned: false,
    attachments: [],
    links: [
      {
        id: "l1",
        label: "Book a Study Room",
        url: "https://knust.edu.gh/library/rooms",
      },
    ],
    comments: [],
  },
  {
    id: "12",
    type: "general",
    title: "Academic Calendar Update – Semester Break Dates",
    body: `The Office of the Registrar has released the updated semester break dates. The semester ends officially on 15th April.\n\nSemester break runs from 16th April to 4th May. Second semester registration opens 28th April online.\n\nStudents are advised to plan travel accordingly and ensure outstanding course work is submitted before the deadline.`,
    author: "Office of the Registrar",
    authorRole: "Administration",
    authorAvatar: null,
    course: null,
    date: "2026-03-08T08:00:00Z",
    dueDate: null,
    commentCount: 8,
    pinned: false,
    attachments: [
      {
        id: "a1",
        name: "Academic_Calendar_2026.pdf",
        type: "pdf",
        size: "320 KB",
      },
    ],
    links: [],
    comments: [],
  },
  {
    id: "13",
    type: "general",
    title: "Counselling Services – Stress Management Workshops",
    body: `Student counselling services will be running free stress management workshops every Tuesday at 2:00 PM throughout the exam period.\n\nSessions are confidential and limited to 15 students. Walk-ins are welcome but booking is advised. The workshop covers breathing techniques, study planning, and managing exam anxiety.\n\nVenue: Student Wellness Centre, Room 4.`,
    author: "Student Affairs",
    authorRole: "Administration",
    authorAvatar: null,
    course: null,
    date: "2026-03-07T10:00:00Z",
    dueDate: null,
    commentCount: 3,
    pinned: false,
    attachments: [],
    links: [
      {
        id: "l1",
        label: "Book a Spot",
        url: "https://knust.edu.gh/wellness/book",
      },
    ],
    comments: [],
  },
  {
    id: "14",
    type: "general",
    title: "Laptop Loan Scheme – Apply Before 20th March",
    body: `Students who require a laptop for exam preparation can apply for the department's short-term laptop loan scheme.\n\nLaptops are available for a 2-week loan period. Priority is given to final-year students. Applications must be submitted with proof of enrollment.\n\nLimited units available — apply early to avoid disappointment.`,
    author: "CSC Department",
    authorRole: "Department",
    authorAvatar: null,
    course: null,
    date: "2026-03-05T14:00:00Z",
    dueDate: "2026-03-20T17:00:00Z",
    commentCount: 14,
    pinned: false,
    attachments: [
      { id: "a1", name: "Laptop_Loan_Form.pdf", type: "pdf", size: "95 KB" },
    ],
    links: [],
    comments: [],
  },
  {
    id: "15",
    type: "general",
    title: "Guest Lecture: AI in Healthcare – 19th March",
    body: `The department is pleased to announce a guest lecture by Dr. Kweku Agyemang, Lead AI Researcher at MedTech Ghana.\n\nTopic: "Practical Applications of Machine Learning in Clinical Diagnostics"\n\nDate: Wednesday 19th March, 3:00 PM – 5:00 PM\nVenue: Lecture Hall A, CS Building\n\nAttendance is optional but highly recommended for students taking AI and ML electives.`,
    author: "Dr. Abena Frimpong",
    authorRole: "Lecturer",
    authorAvatar: null,
    course: null,
    date: "2026-03-04T09:00:00Z",
    dueDate: null,
    commentCount: 19,
    pinned: false,
    attachments: [],
    links: [
      {
        id: "l1",
        label: "Register for Lecture",
        url: "https://forms.google.com/ai-lecture-rsvp",
      },
    ],
    comments: [],
  },
  {
    id: "16",
    type: "general",
    title: "Wi-Fi Maintenance – Network Downtime Saturday Night",
    body: `Campus Wi-Fi will be undergoing scheduled maintenance on Saturday 22nd March between 11:00 PM and 3:00 AM.\n\nDuring this window, internet access will be unavailable across all campus buildings including the library and hostels.\n\nPlan your downloads and cloud submissions before this window. The IT helpdesk will be available from Sunday 9:00 AM if issues persist.`,
    author: "IT Services",
    authorRole: "Administration",
    authorAvatar: null,
    course: null,
    date: "2026-03-13T15:00:00Z",
    dueDate: null,
    commentCount: 6,
    pinned: false,
    attachments: [],
    links: [],
    comments: [],
  },

  // ── Assignments ──────────────────────────────────────────────────────────────
  {
    id: "6",
    type: "assignment",
    title: "ENG 201: Technical Report Submission",
    body: `Your technical report for ENG 201 must be submitted by the due date. Ensure you follow the prescribed format as outlined in the course handbook.\n\nReports must be uploaded as PDF files via the submission portal. Submissions that do not follow the format will be returned without grading.\n\nWord limit: 2500–3000 words. Include a cover page, table of contents, and references section.`,
    author: "Prof. Asante",
    authorRole: "Lecturer",
    authorAvatar: null,
    course: "ENG 201",
    date: "2026-03-04T10:00:00Z",
    dueDate: "2026-03-23T23:59:00Z",
    commentCount: 3,
    pinned: false,
    attachments: [
      {
        id: "a1",
        name: "ENG201_Report_Format.pdf",
        type: "pdf",
        size: "320 KB",
      },
    ],
    links: [
      {
        id: "l1",
        label: "Report Submission Portal",
        url: "https://knust.edu.gh/student/submit",
      },
    ],
    comments: [],
  },
  {
    id: "9",
    type: "assignment",
    title: "CSC 412: Software Engineering Group Project – Phase 2",
    body: `Phase 2 of the Software Engineering group project is due soon. Your submission must include:\n\n- System design document (UML class diagram, use case diagram)\n- Updated ER diagram reflecting any changes from Phase 1 feedback\n- Sprint 2 review report (what was planned vs completed)\n- Updated GitHub repository link\n\nAll group members must be listed on the cover page. Only one submission per group.`,
    author: "Dr. Ofori-Mensah",
    authorRole: "Lecturer",
    authorAvatar: null,
    course: "CSC 412",
    date: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    dueDate: "2026-03-22T17:00:00Z",
    commentCount: 11,
    pinned: false,
    attachments: [
      {
        id: "a1",
        name: "Phase2_Requirements.pdf",
        type: "pdf",
        size: "412 KB",
      },
    ],
    links: [
      {
        id: "l1",
        label: "Group Project Submission Portal",
        url: "https://knust.edu.gh/student/submit",
      },
      {
        id: "l2",
        label: "Phase 1 Feedback Sheet",
        url: "https://docs.google.com/spreadsheets/d/example",
      },
    ],
    comments: [
      {
        id: "c1",
        author: "Selorm Agyei",
        authorRole: "Student",
        body: "Do we need to submit the GitHub link as a separate document or just paste the URL in the report?",
        date: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
        replies: [
          {
            id: "c1r1",
            author: "Dr. Ofori-Mensah",
            authorRole: "Lecturer",
            body: "Paste it clearly on the cover page and also inside the sprint review report.",
            date: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
            replies: [],
          },
        ],
      },
    ],
  },
  {
    id: "17",
    type: "assignment",
    title: "CSC 302: Operating Systems – Shell Scripting Lab",
    body: `Write a Bash shell script that monitors CPU and memory usage every 5 seconds and logs the output to a file with timestamps.\n\nAdditionally, the script should send an alert (echo message) when CPU usage exceeds 80%.\n\nSubmit a single .sh file with your student ID as the filename. Late submissions attract a 15% penalty per day.`,
    author: "Dr. Yaa Asantewaa",
    authorRole: "Lecturer",
    authorAvatar: null,
    course: "CSC 302",
    date: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    dueDate: "2026-03-24T23:59:00Z",
    commentCount: 9,
    pinned: false,
    attachments: [
      {
        id: "a1",
        name: "Lab_Instructions_Shell.pdf",
        type: "pdf",
        size: "185 KB",
      },
    ],
    links: [
      {
        id: "l1",
        label: "Lab Submission Portal",
        url: "https://knust.edu.gh/student/submit",
      },
    ],
    comments: [],
  },
  {
    id: "18",
    type: "assignment",
    title: "CSC 305: Database Design – ER Diagram Submission",
    body: `Submit your Entity-Relationship diagram for the hospital management system case study discussed in Week 6.\n\nYour diagram must clearly show:\n- All entities and their attributes\n- Relationships with correct cardinality\n- Primary and foreign keys highlighted\n\nAccepted formats: PDF or PNG. Use draw.io, Lucidchart, or any UML tool of your choice.`,
    author: "Kwame Asante",
    authorRole: "Course Rep",
    authorAvatar: null,
    course: "CSC 305",
    date: "2026-03-11T10:00:00Z",
    dueDate: "2026-03-26T17:00:00Z",
    commentCount: 4,
    pinned: false,
    attachments: [],
    links: [
      {
        id: "l1",
        label: "Submission Portal",
        url: "https://knust.edu.gh/student/submit",
      },
    ],
    comments: [],
  },
  {
    id: "19",
    type: "assignment",
    title: "CSC 410: Machine Learning – Mini Project Proposal",
    body: `Submit a 1–2 page project proposal for your ML mini project. The proposal must include:\n\n- Problem statement\n- Chosen dataset (with source)\n- Planned model(s) to explore\n- Evaluation metrics you will use\n\nProposals will be reviewed and feedback provided within 5 working days. Full project submission is due Week 13.`,
    author: "Prof. Kweku Boateng",
    authorRole: "Lecturer",
    authorAvatar: null,
    course: "CSC 410",
    date: "2026-03-09T09:00:00Z",
    dueDate: "2026-03-27T23:59:00Z",
    commentCount: 16,
    pinned: false,
    attachments: [
      {
        id: "a1",
        name: "ML_Project_Guidelines.pdf",
        type: "pdf",
        size: "210 KB",
      },
    ],
    links: [
      {
        id: "l1",
        label: "Kaggle Datasets",
        url: "https://www.kaggle.com/datasets",
      },
      {
        id: "l2",
        label: "Submission Portal",
        url: "https://knust.edu.gh/student/submit",
      },
    ],
    comments: [],
  },
  {
    id: "20",
    type: "assignment",
    title: "MTH 203: Linear Algebra – Problem Set 4",
    body: `Problem Set 4 covers topics from Weeks 8–10: eigenvalues, eigenvectors, diagonalisation, and orthogonality.\n\nThere are 8 questions. Show all working — answers without working will not receive full marks.\n\nHandwritten submissions are accepted. Scan and upload as a single PDF. Minimum resolution: 300 DPI.`,
    author: "Dr. Mensah-Bonsu",
    authorRole: "Lecturer",
    authorAvatar: null,
    course: "MTH 203",
    date: "2026-03-06T11:00:00Z",
    dueDate: "2026-03-25T23:59:00Z",
    commentCount: 7,
    pinned: false,
    attachments: [
      { id: "a1", name: "Problem_Set_4.pdf", type: "pdf", size: "140 KB" },
    ],
    links: [],
    comments: [],
  },
  {
    id: "21",
    type: "assignment",
    title: "CSC 308: Computer Networks – Packet Tracer Lab 3",
    body: `Configure a small enterprise network in Cisco Packet Tracer with the following:\n\n- 2 routers, 3 switches, 8 end devices\n- VLAN segmentation (HR, Finance, IT)\n- Inter-VLAN routing via Router-on-a-Stick\n- OSPF dynamic routing between the two routers\n\nExport your .pkt file and submit along with a brief network description document.`,
    author: "Dr. K. Mensah",
    authorRole: "Lecturer",
    authorAvatar: null,
    course: "CSC 308",
    date: "2026-03-03T14:00:00Z",
    dueDate: "2026-03-28T23:59:00Z",
    commentCount: 12,
    pinned: false,
    attachments: [
      { id: "a1", name: "Lab3_Starter.pkt", type: "pdf", size: "38 KB" },
      {
        id: "a2",
        name: "Network_Description_Template.docx",
        type: "pdf",
        size: "52 KB",
      },
    ],
    links: [
      {
        id: "l1",
        label: "Submission Portal",
        url: "https://knust.edu.gh/student/submit",
      },
    ],
    comments: [],
  },
  {
    id: "22",
    type: "assignment",
    title: "CSC 201: Algorithms – Sorting Complexity Analysis",
    body: `Analyse the time and space complexity of Bubble Sort, Merge Sort, and Quick Sort.\n\nFor each algorithm:\n- Write the recurrence relation\n- Solve using the Master Theorem where applicable\n- Provide a best, average, and worst-case analysis\n- Include a comparison table\n\nSubmit as a PDF report (max 5 pages).`,
    author: "Ama Owusu",
    authorRole: "Course Rep",
    authorAvatar: null,
    course: "CSC 201",
    date: "2026-02-25T09:00:00Z",
    dueDate: "2026-03-21T23:59:00Z",
    commentCount: 5,
    pinned: false,
    attachments: [],
    links: [],
    comments: [],
  },

  // ── Exams ────────────────────────────────────────────────────────────────────
  {
    id: "3",
    type: "exam",
    title: "CSM 342 – Networking Fundamentals Mid-Semester Exam",
    body: `Mid-semester examination covering Weeks 1–7. Multiple choice and short answer sections.\n\nTopics include: OSI model, TCP/IP stack, subnetting, routing protocols (RIP, OSPF), and switching fundamentals.\n\nStudents are advised to bring a valid student ID. No electronic devices allowed in the exam hall.`,
    author: "Dr. K. Mensah",
    authorRole: "Lecturer",
    authorAvatar: null,
    course: "CSM 342",
    date: "2026-02-23T08:00:00Z",
    dueDate: "2026-03-25T09:00:00Z",
    commentCount: 7,
    pinned: false,
    attachments: [],
    links: [
      {
        id: "l1",
        label: "Past Questions – Networking",
        url: "https://knust.edu.gh/library/past-questions",
      },
    ],
    comments: [
      {
        id: "c1",
        author: "Priscilla Adu",
        authorRole: "Student",
        body: "Will VLAN configuration be included in the exam scope?",
        date: "2026-02-24T10:00:00Z",
        replies: [],
      },
    ],
  },
  {
    id: "7",
    type: "exam",
    title: "MTH 101: Calculus Resit Examination",
    body: `Students who did not pass the MTH 101 Calculus examination are reminded that the resit is scheduled in Hall B at 8:00 AM.\n\nPlease bring your student ID card. The exam covers all topics from the original paper: limits, derivatives, integration techniques, and applications.\n\nAny student who misses the resit without a medical certificate will forfeit their supplementary opportunity.`,
    author: "Mathematics Department",
    authorRole: "Department",
    authorAvatar: null,
    course: "MTH 101",
    date: "2026-03-03T11:00:00Z",
    dueDate: "2026-03-30T08:00:00Z",
    commentCount: 5,
    pinned: false,
    attachments: [],
    links: [],
    comments: [],
  },
  {
    id: "23",
    type: "exam",
    title: "CSC 303: Database Systems – Mid-Semester Exam Notice",
    body: `The mid-semester examination for CSC 303 will be held on 26th March at 10:00 AM in Lecture Hall B.\n\nCoverage: Weeks 1–8. Topics include ER modelling, relational algebra, SQL (DDL and DML), normalisation up to 3NF, and transaction management.\n\nOpen-book policy does NOT apply. Only your student ID card is permitted.`,
    author: "Dr. Ofori-Mensah",
    authorRole: "Lecturer",
    authorAvatar: null,
    course: "CSC 303",
    date: "2026-03-12T08:00:00Z",
    dueDate: "2026-03-26T10:00:00Z",
    commentCount: 11,
    pinned: false,
    attachments: [
      { id: "a1", name: "DB_Exam_Scope.pdf", type: "pdf", size: "165 KB" },
    ],
    links: [
      {
        id: "l1",
        label: "Past Questions",
        url: "https://knust.edu.gh/library/past-questions",
      },
    ],
    comments: [],
  },
  {
    id: "24",
    type: "exam",
    title: "CSC 201: Algorithms – End of Semester Exam Date Confirmed",
    body: `The end-of-semester exam for CSC 201 is confirmed for 8th April at 9:00 AM in Hall A.\n\nFull syllabus applies: sorting, searching, graph algorithms (BFS, DFS, Dijkstra), dynamic programming, and NP-completeness.\n\nA formula sheet will NOT be provided. Students should prepare to recall all complexity functions and proofs.`,
    author: "Prof. Kweku Boateng",
    authorRole: "Lecturer",
    authorAvatar: null,
    course: "CSC 201",
    date: "2026-03-10T10:00:00Z",
    dueDate: "2026-04-08T09:00:00Z",
    commentCount: 9,
    pinned: false,
    attachments: [],
    links: [],
    comments: [],
  },
  {
    id: "25",
    type: "exam",
    title: "ENG 201: Engineering Mathematics Exam – Venue Change",
    body: `Please note that the ENG 201 exam originally scheduled for Hall C has been moved to the Sports Complex Hall due to renovation works.\n\nDate and time remain the same: 2nd April at 11:00 AM.\n\nStudents who face transport or access difficulties should contact the engineering office by 30th March.`,
    author: "Prof. Asante",
    authorRole: "Lecturer",
    authorAvatar: null,
    course: "ENG 201",
    date: "2026-03-09T13:00:00Z",
    dueDate: "2026-04-02T11:00:00Z",
    commentCount: 6,
    pinned: false,
    attachments: [],
    links: [],
    comments: [],
  },
  {
    id: "26",
    type: "exam",
    title: "CSC 410: Machine Learning – Practical Exam Guidelines",
    body: `The CSC 410 practical exam will be held in Lab 2 on 5th April at 2:00 PM.\n\nYou will be given a dataset and asked to train, evaluate, and interpret a machine learning model within 2 hours. Libraries permitted: scikit-learn, pandas, numpy, matplotlib.\n\nNo internet access during the exam. Bring your student ID.`,
    author: "Prof. Kweku Boateng",
    authorRole: "Lecturer",
    authorAvatar: null,
    course: "CSC 410",
    date: "2026-03-08T09:00:00Z",
    dueDate: "2026-04-05T14:00:00Z",
    commentCount: 13,
    pinned: false,
    attachments: [
      {
        id: "a1",
        name: "Practical_Exam_Guidelines.pdf",
        type: "pdf",
        size: "195 KB",
      },
    ],
    links: [],
    comments: [],
  },
  {
    id: "27",
    type: "exam",
    title: "MTH 203: Linear Algebra – Exam Scope Clarification",
    body: `Following questions raised in class, here is a clarification on the scope for the Linear Algebra exam:\n\nIncluded: Vectors, matrices, determinants, systems of equations, eigenvalues/eigenvectors, diagonalisation.\n\nNot included: Tensor products, Fourier series, and advanced inner product spaces (these are postgraduate topics).\n\nPast papers are available at the library and will be discussed in the revision lecture on 28th March.`,
    author: "Dr. Mensah-Bonsu",
    authorRole: "Lecturer",
    authorAvatar: null,
    course: "MTH 203",
    date: "2026-03-06T10:00:00Z",
    dueDate: "2026-04-03T09:00:00Z",
    commentCount: 21,
    pinned: false,
    attachments: [],
    links: [
      {
        id: "l1",
        label: "Past Papers – Library Portal",
        url: "https://knust.edu.gh/library/past-questions",
      },
    ],
    comments: [],
  },
  {
    id: "28",
    type: "exam",
    title: "CSC 302: Operating Systems – Revision Lecture on 27th March",
    body: `A revision lecture for the OS exam will be held on 27th March at 1:00 PM in Lecture Room 7.\n\nTopics to be covered: process scheduling, memory management (paging, segmentation), deadlocks, and file systems.\n\nBring your questions. The session will be recorded and uploaded to the portal within 24 hours.`,
    author: "Dr. Yaa Asantewaa",
    authorRole: "Lecturer",
    authorAvatar: null,
    course: "CSC 302",
    date: "2026-03-05T14:00:00Z",
    dueDate: "2026-04-01T09:00:00Z",
    commentCount: 8,
    pinned: false,
    attachments: [],
    links: [
      {
        id: "l1",
        label: "Course Portal",
        url: "https://knust.edu.gh/courses/csc302",
      },
      {
        id: "l2",
        label: "Course Portal",
        url: "https://knust.edu.gh/courses/csc3402",
      },
    ],
    comments: [],
  },
  {
    id: "29",
    type: "exam",
    title: "CSC 308: Networks – Exam Registration Reminder",
    body: `Students must confirm their exam registration for CSC 308 via the student portal no later than 21st March.\n\nFailure to register will result in not being listed on the exam script sheet, which may delay your results.\n\nIf you encounter any portal issues, visit the examination office with your student ID by 20th March.`,
    author: "Examinations Office",
    authorRole: "Administration",
    authorAvatar: null,
    course: "CSC 308",
    date: "2026-03-01T09:00:00Z",
    dueDate: "2026-03-21T17:00:00Z",
    commentCount: 4,
    pinned: false,
    attachments: [],
    links: [
      {
        id: "l1",
        label: "Student Portal",
        url: "https://knust.edu.gh/student/portal",
      },
    ],
    comments: [],
  },
  {
    id: "30",
    type: "exam",
    title: "CSC 395: Data Structures – Practical Component Details",
    body: `The Data Structures course has a practical component worth 30% of the final grade.\n\nThe practical exam will be held in the CS Lab on 3rd April at 10:00 AM. You will be required to implement and demonstrate a data structure of your choice from the syllabus.\n\nLanguage: Python or Java. Duration: 90 minutes. No reference materials allowed.`,
    author: "Dr. Abena Frimpong",
    authorRole: "Lecturer",
    authorAvatar: null,
    course: "CSC 395",
    date: "2026-02-27T09:00:00Z",
    dueDate: "2026-04-03T10:00:00Z",
    commentCount: 10,
    pinned: false,
    attachments: [],
    links: [],
    comments: [],
  },
];

export const mockDeadlines = [
  {
    id: "d1",
    title: "CSC 395: AVL Trees Assignment",
    course: "CSC 395",
    dueDate: "2026-03-22T23:59:00Z",
    type: "assignment",
  },
  {
    id: "d2",
    title: "ENG 201: Technical Report",
    course: "ENG 201",
    dueDate: "2026-03-23T23:59:00Z",
    type: "assignment",
  },
  {
    id: "d3",
    title: "CSC 412: SE Group Project Phase 2",
    course: "CSC 412",
    dueDate: "2026-03-22T17:00:00Z",
    type: "assignment",
  },
  {
    id: "d4",
    title: "CSM 342: Networking Mid-Semester Exam",
    course: "CSM 342",
    dueDate: "2026-03-25T09:00:00Z",
    type: "exam",
  },
  {
    id: "d5",
    title: "Mid-Semester Examinations Begin",
    course: null,
    dueDate: "2026-03-26T08:00:00Z",
    type: "general",
  },
  {
    id: "d6",
    title: "MTH 101 Resit Exam",
    course: "MTH 101",
    dueDate: "2026-03-30T08:00:00Z",
    type: "exam",
  },
  {
    id: "d7",
    title: "CSC 303: Database Systems Exam",
    course: "CSC 303",
    dueDate: "2026-03-26T10:00:00Z",
    type: "exam",
  },
  {
    id: "d8",
    title: "CSC 302: OS Shell Scripting Lab",
    course: "CSC 302",
    dueDate: "2026-03-24T23:59:00Z",
    type: "assignment",
  },
  {
    id: "d9",
    title: "MTH 203: Linear Algebra Problem Set 4",
    course: "MTH 203",
    dueDate: "2026-03-25T23:59:00Z",
    type: "assignment",
  },
  {
    id: "d10",
    title: "CSC 308: Networks Exam Registration",
    course: "CSC 308",
    dueDate: "2026-03-21T17:00:00Z",
    type: "exam",
  },
  {
    id: "d11",
    title: "CSC 201: Algorithms End-of-Semester Exam",
    course: "CSC 201",
    dueDate: "2026-04-08T09:00:00Z",
    type: "exam",
  },
  {
    id: "d12",
    title: "CSC 410: ML Practical Exam",
    course: "CSC 410",
    dueDate: "2026-04-05T14:00:00Z",
    type: "exam",
  },
  {
    id: "d13",
    title: "CSC 303: Database Systems Final Exam",
    course: "CSC 303",
    dueDate: "2026-04-05T09:00:00Z",
    type: "exam",
  },
];
